### ISSUE TITLE
Make it cross platform

### ISSUE THREAD

**Issue by OpResCodes** [sdcb/Sdcb.WordCloud#1]
Hi, great library!
Any chance that you can make it run cross platform? The dependency on System.Drawing makes it Windows only and maybe it could be converted with SkiaSharp..

**Comment by sdcb** [comment]
Thank you for your attention. I will give it a try.

**Comment by sdcb** [comment]
Hi @OpResCodes , Sdcb.WordCloud should be cross platform by now, it's been completely rewrite, it uses SkiaSharp, can you take a look?
